### ISSUE TITLE
Create an automated ci test

### ISSUE THREAD

**Issue by jam01** [MS3Inc/tavros#2]
We have a test-playbook.yaml that is tested locally. In order to enable continuous integration we need to add some assertions and create a Jenkins job to be run on demand. 

The test playbook should:
- [x] provision kubernetes infrastructure from scratch
- [x] setup our default components
- [ ] deploy a test application and run assertions against supported components, eg.: mesh isolation, https instead of http, etc
- [x] destroy the kubernetes infrastructure
- [ ] be an on-demand ci job
